# Generated by Django 4.0 on 2024-07-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articulos',
            new_name='articulo',
        ),
    ]
